server:
  port: 8080
  servlet:
    context-path: /boiler-plate
spring:
  application:
    name: boilerPlate

  datasource:
    url: jdbc:postgresql://localhost:5432/boilerPlate
    username: postgres
    password: suraj
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
